name: mirmachine
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.29.2
  - coreutils=8.31
  - django=3.2.6
  - gawk=5.0.1
  - moreutils=0.65
  - pip=20.0.2
  - python=3.8
  - samtools=1.9
  - infernal=1.1.2
  - pip:
    - appdirs==1.4.3
    - attrs==19.3.0
    - biopython==1.76
    - channels==3.0.4
    - channels-redis==3.3.1
    - configargparse==1.1
    - datrie==0.8.2
    - decorator==4.4.2
    - django-manifest-loader==1.0.0
    - djangorestframework==3.12.4
    - docopt==0.6.2
    - docutils==0.16
    - gitdb==4.0.2
    - gitpython==3.1.0
    - importlib-metadata==1.5.0
    - ipython-genutils==0.2.0
    - jsonschema==3.2.0
    - jupyter-core==4.6.3
    - nbformat==5.0.4
    - newick==1.0.0
    - numpy==1.18.2
    - psutil==5.7.0
    - pyrsistent==0.15.7
    - pyyaml==5.3.1
    - ratelimiter==1.2.0.post0
    - smmap==3.0.1
    - snakemake==5.11.1
    - toposort==1.5
    - traitlets==4.3.3
    - wrapt==1.12.1
    - zipp==3.1.0
